# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :sequence, 1000
test :random, 1000, 5
test :random, 100, 50
test :random, 10, 500
10.times do
  test :random, 1, 5000
end
test '002.hand'
