# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :sequence, 10000
test :random, 10000, 5
test :random, 1000, 50
test :random, 100, 500
test :random, 10, 5000
test :nine, n: 5000

add_target :solution_zimpha
