# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

1.upto(5) do |n|
  test :small, n: n
end
test :random, T: 10_000, n: 17, maxm: 20
test :random, T: 1000, n: (200 * 0.99).to_i, maxm: 200
test :random, T: 100, n: (2000 * 0.99).to_i, maxm: 2000
test :random, T: 10, n: (20_000 * 0.99).to_i, maxm: 20_000
test :random, T: 1, n: 100_000, maxm: 200_000

add_target :very_slow
