# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :generate, type: :random, T: 100, n: 1000, maxw: 10_000, q: 100, k: 1000, kw: 0
test :generate, type: :random, T: 100, n: 100, maxw: 10_000, q: 1000, k: 1000, kw: 0
test :generate, type: :random, T: 100, n: 1000, maxw: 10_000, q: 1000, k: 1000, kw: 0
test :generate, type: :path,   T: 1,   n: 100_000, maxw: 10_000, q: 100_000, k: 100_000, kw: 0
test :generate, type: :random, T: 1,   n: 100_000, maxw: 10_000, q: 100_000, k: 100_000, kw: 0
test :generate, type: :random, T: 1,   n: 100_000, maxw: 10_000, q: 100_000, k: 100_000, kw: 10
test :generate, type: :random, T: 1,   n: 100_000, maxw: 10_000, q: 100_000, k: 100_000, kw: 100
test :generate, type: :random, T: 1,   n: 100_000, maxw: 10_000, q: 100_000, k: 100_000, kw: 100_000

add_target :slow
add_target :solution_nero
