# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'
test :random, T: 10, n: 5
test :random, T: 5, n: 10
10.times do |w|
  test :long, T: 1, n: 50, w: w + 1
end
test :random, T: 1, n: 50
test :random, T: 1, n: 50, id: true

add_target :slow
add_target :slow_231
