# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'
test :gen, 2, 2, 10
test :gen, 3, 3, 10
test :gen, 4, 4, 10
test :gen, 5, 5, 10
test :gen, 6, 6, 10
test :gen, 7, 7, 10
test :gen, 8, 8, 10
test :gen, 9, 9, 10
test :gen, 10, 10, 10
test :gen, 2, 10, 100
test :gen, 10, 20, 100
test :gen, 90, 110, 100
test :gen, 90, 110, 10_000
test :gen, 90, 110, 1_000_000
test :gen, 50, 100, 100
test :gen, 50, 100, 10_000
test :gen, 50, 100, 1_000_000
test :gen, 200, 250, 100
test :gen, 240, 250, 10_000
test :gen, 250, 250, 1_000_000

add_target :slow
add_target :solution_nero
