# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test '002.hand'
test :random, T: 10_000, maxn: 20, maxm: 20
test :random, T: 1000, maxn: 200, maxm: 200
test :random, T: 100, maxn: 2000, maxm: 2000
test :random, T: 10, n: 20_000, m: 20_000
test :random, T: 1, n: 200_000, m: 200_000, maxlen: 20
test :random, T: 1, n: 200_000, m: 200_000, maxlen: 200
test :random, T: 1, n: 200_000, m: 200_000, maxlen: 2000
test :random, T: 1, n: 200_000, m: 200_000, maxlen: 20_000
test :random, T: 1, n: 200_000, m: 200_000

add_target :slow
add_target :solution_ftiasch
add_target :solution_ftiasch_linear
