# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :random, T: 100_000, maxn: 2, q: 2
test :random, T: 10_000, maxn: 20, q: 20
test :random, T: 1000, maxn: 200, q: 200
test :random, T: 100, maxn: 2000, q: 2000
test :random, T: 10, n: 20_000, q: 20_000
10.times do
  test :random, T: 1, n: 200_000, q: 200_000
end

add_target :slow
add_target :very_slow
add_target :solution_nero
