# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :random, T: 10_000, n: 20, q: 20
test :random, T: 1000, n: 20, q: 200
test :random, T: 1000, n: 200, q: 20
test :random, T: 1000, n: 200, q: 200
test :random, T: 100, n: 2000, q: 2000
test :random, T: 10, n: 20_000, q: 20_000
test :random, T: 1, n: 200_000, q: 200_000

add_target :slow
add_target :very_slow
