# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test '002.hand'
[100, 1000].each do |t|
  test :random, T: t, n: 200_000 / t, v: 100_000, vt: 5000
end
test :random, T: 10, n: 20_000, v: 200_000, vt: 2500, colinear: true
test :random, T: 1, n: 200_000, v: 200_000, vt: 2500, colinear: true

add_target :very_slow
add_target :slow
add_target :wrong
