# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test '002.hand'
test :random, T: 10_000, maxn: 20, v: 100_000, vt: 5000
test :random, T: 1000, maxn: 200, v: 100_000, vt: 5000
test :random, T: 100, maxn: 2_000, v: 100_000, vt: 5000
test :random, T: 10, n: 20_000, v: 200_000, vt: 2500, colinear: true
test :random, T: 1, n: 200_000, v: 200_000, vt: 2500, colinear: true

add_target :very_slow
add_target :slow
add_target :wrong
