# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :random, T: 10_000, n: 200, minord: 0, maxord: 2015
test :random, T: 1000, n: 2000, minord: 1, maxord: 1000
test :random, T: 100, n: 20_000, minord: 1, maxord: 100
test :random, T: 10, n: 200_000, minord: 1, maxord: 10
10.times do
  test :random, T: 1, n: 2_000_000, minord: 1, maxord: 2
end

add_target :slow
add_target :solution_nero
