require_relative '../../common'

sample '001.hand'

test :generate, :random, 100, 10 ** 3, 10 ** 4, 10 ** 3, 10 ** 3, 0
test :generate, :path, 1, 10 ** 5, 10 ** 4, 10 ** 5, 10 ** 5, 0
test :generate, :random, 1, 10 ** 5, 10 ** 4, 10 ** 5, 10 ** 5, 0
test :generate, :random, 1, 10 ** 5, 10 ** 4, 10 ** 5, 10 ** 5, 10
test :generate, :random, 1, 10 ** 5, 10 ** 4, 10 ** 5, 10 ** 5, 100
test :generate, :random, 1, 10 ** 5, 10 ** 4, 10 ** 5, 10 ** 5, 10 ** 5

add_target :slow
add_target :solution_nero
