# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :random, 20_000 - 2, 10, 0
test :random, 2_000, 100, 0
test :random, 200, 1_000, 0
test :random, 20, 10_000, 0
test :random, 2, 100_000, 0
20.times do
  test :random, 1, 1_000_000, 0
end
test :big_asc, 1, 1_000_000, 100_000
test :big_asc, 1, 1_000_000, 10_000
test :big_asc, 1, 1_000_000, 1000

add_target :slow
