# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :random, T: 10_000, maxn: 1
test :random, T: 10_000, maxn: 10
test :random, T: 1000, maxn: 100
test :random, T: 100, maxn: 1000
test :random, T: 10, n: 10_000
10.times do
  test :random, T: 1, n: 100_000
end

add_target :solution_nero
