# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

Q = 100_000

test :random, T: 16 * 16 * 16, m: 4, q: Q / (16 * 16 * 16)
test :random, T: 16 * 16, m: 8, q: Q / (16 * 16)
test :random, T: 16, m: 12, q: Q / 16
test :random, T: 1, m: 16, q: Q

add_target :slow
add_target :solution_nero
