# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'
test :random, T: 1, n: 100, m: 100, k: 5, w: 10, h: 10, v: 50
test :random, T: 1, n: 2000, m: 2000, k: 5, w: 1000, h: 1000, v: 1_000_000_000

add_target :slow_rmq
add_target :slow_set
add_target :slow_set_ftiasch
add_target :very_slow
