# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :random, T: 50_000, maxn: 4, m: 6
test :random, T: 10_000, maxn: 20, m: 20
test :random, T: 1000, maxn: 200, m: 200
test :random, T: 100, maxn: 2_000, m: 2000
test :random, T: 10, n: 20_000, m: 20_000
test :random, T: 1, n: 200_000, m: 200_000
test :clustered, n: 2000, m: 200_000, w: 50
test :clustered, n: 5000, m: 200_000, w: 500
test :bipartite, n0: 10, n1: 200_000 - 10, m: 200_000
test :bipartite, n0: 500, n1: 500, m: 200_000

add_target :solution_nero
add_target :slow
add_target :slow2
add_target :slow3
