# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :random, T: 4000, n: 20, m: 50
test :random, T: 1000, n: 100, m: 200
test :random, T: 100, n: 1000, m: 2000
test :random, T: 10, n: 10_000, m: 20_000
test :random, T: 1, n: 100_000, m: 200_000
test :random, T: 1, n: 200_000, m: 200_000

add_target :slow
