# frozen_string_literal: true

require_relative '../../common'

sample '001.hand'

test :random, T: 200_000, maxn: 1, w: 0
test :random, T: 10_000, maxn: 20, w: 0
test :random, T: 1000, maxn: 200, w: 0
test :random, T: 100, maxn: 2000, w: 0
test :random, T: 10, n: 20_000, w: 0
5.times do
  test :random, T: 1, n: 200_000, w: 0
  test :random, T: 1, n: 200_000, w: 200_000
end

add_target :slow
add_target :wrong
add_target :solution_nero
